ekf_filter_node:
  ros__parameters:

    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    publish_tf: true
    publish_acceleration: false

    # =========================
    # Frames
    # =========================
    map_frame: map              # ไม่ได้ใช้จริง แต่ต้องมี
    odom_frame: odom_sync
    base_link_frame: base_footprint_sync
    world_frame: odom_sync      # << สำคัญมาก (local EKF)

    # =========================
    # Odometry from RF2O
    # =========================
    odom0: /odom_rf2o
    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false, true,    # roll, pitch, yaw
      true,  true,  false,   # vx, vy, vz
      false, false, true,    # vroll, vpitch, vyaw
      false, false, false
    ]

    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # =========================
    # IMU
    # =========================
    imu0: /imu_sync
    imu0_config: [
      false, false, false,   # position (ignore)
      false, false, true,    # roll, pitch, yaw (use yaw only)
      false, false, false,   # linear velocity
      false, false, true,    # angular velocity (yaw rate)
      false, false, false
    ]

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    




# /odometry/filtered
#    ----> TF
#           -------> (odom_sync  ─────▶  base_footprint_sync)


# ros2 topic info /odometry/filtered -v
# Type: nav_msgs/msg/Odometry

# Publisher count: 1

# Node name: ekf_filter_node
# Node namespace: /
# Topic type: nav_msgs/msg/Odometry
